### ISSUE TITLE
LANrev

### ISSUE THREAD

**Issue by jfuchtm** [autopkg/seansgm-recipes#1]
Will a new LANrev processor be release by AutoPkgr taking the place of the Absolute one currently in place?  I noticed none of the new LANrev recipes work on the current system. 

Thanks and keep up the LANrev recipes, they are a huge time saver.

-Jeff

**Comment by seansgm** [comment]
According to the guys on the Slack channel, they are hoping to have an update to reflect this in V1.4

**Comment by jfuchtm** [comment]
Thanks for the update.
