### ISSUE TITLE
VLC

### ISSUE THREAD

**Issue by jfuchtm** [autopkg/seansgm-recipes#4]
The VLC recipe will not update to the latest due to the latest version lookup at http://update.videolan.org/vlc/sparkle/vlc-intel64.xml.  Appears the XML has not been updated in sometime.

Thanks
-Jeff

**Comment by patgmac** [comment]
The VLC folks don't update the sparkle feed until they deem it fully stable. This has been the case with previous versions as well.

**Comment by seansgm** [comment]
Sorry Jeff, been off the scene for a while.  As Pat mentioned, this is typical of VLC.   Also, all of these LANrev recipes just pull from parent recipes hosted by other contributors.  For incorrect downloads, it would be recommended to contact the owner of the download recipe.
