### ISSUE TITLE
Error PlistReader Processor

### ISSUE THREAD

**Issue by andredb90** [autopkg/seansgm-recipes#6]
Hi, I'm getting following Error when using your recipe.

Processor: PlistReader: Error: Path '/Users/admin/Library/AutoPkg/Cache/local.filewave.AdobeReaderDC/application_payload/Applications/Adobe Acrobat Reader DC.app' doesn't exist!

Is there anything we can do about it?

Thank you and best regards
andre

**Comment by sean-alex** [comment]
I also get same error when using that recipe.
